name: Go
on: 
  schedule:
    - cron: "50 4 * * *"
jobs:

  report:
    name: Self report
    runs-on: ubuntu-latest
    steps:

    - name: Get executable
      run: |
        wget -O auto-self-report https://github.com/mzz2017/auto-selfreport/releases/download/v1.0.2/auto-selfreport_linux_amd64
        chmod +x auto-self-report
        
    - name: Run job
      run: ./auto-self-report -u ${{ secrets.SHU_USERNAME }} -p ${{ secrets.SHU_PASSWORD }} -e kastnerorz@gmail.com
