name: Auto Self Report
on: 
  schedule:
    - cron: "0 1 * * *"
jobs:

  report:
    name: Self report
    runs-on: ubuntu-latest
    steps:

    - name: Get executable
      run: |
        curl -s https://api.github.com/repos/mzz2017/auto-selfreport/releases/latest | grep "auto-selfreport_linux_amd64" | cut -d : -f 2,3 | tr -d \" | wget -O auto-self-report -qi -
        chmod +x auto-self-report
        
    - name: Run job
      run: ./auto-self-report -u ${{ secrets.SHU_USERNAME }} -p ${{ secrets.SHU_PASSWORD }} -e ${{ secrets.EMAIL }}
